### ISSUE TITLE
TV Updating Error

### ISSUE THREAD

**Issue by AsianInvader** [tjoskar/script.episodeHunter#14]
When trying to manually update the watched tv shows in Kodi to EpisodeHunter, an error returns:
'List' Object Has no Attribute 'IterItems'

**Comment by tjoskar** [comment]
Is it possible that you haven't markt anything as watched on episodehunter.tv before you tried to synchronized your Kodi library?

What OS are you using? Windiws? Mac? Linux? 

This is clearly a bug in which case. Thanks for pointing it out.

**Comment by AsianInvader** [comment]
I already had a lot synced to episodehunter.tv
I am using Windows 7

I manually removed all of the incorrectly added episodes from my
episodehunter.tv account and tested some more:
This functions properly for updating episodehunter.tv when automatically
scrobbling from watching an episode
However when clicking on the manual updates:

   - Movie updating works properly
   - Episode updating requests to mark the unwatched portion of the library
   as watched in episodehunter.tv

**Comment by tjoskar** [comment]
Do you still get the error message when you try to sync?

I just managed to reproduced the bug. I will track it down and kill it.
