### ISSUE TITLE
Error with SYNC WATCHED TV EPISODES

### ISSUE THREAD

**Issue by AsianInvader** [tjoskar/script.episodeHunter#15]
On 64bit Windows 7, running Kodi 14.1:
When selecting SYNC WATCHED TV EPISODES, I constantly receive the error: 'NONETYPE' OBJECT IS NOT ITERABLE

**Comment by tjoskar** [comment]
What version of episodehunter-addon do you use? You can see it on the right hand side on the video-addon page. It should be `1.1.2`.

Does this error appear immediately when you press "Sync watched TV episodes" or does it take a while? 

I have parsed your information on eh and can not find any errors so I believe that I take some erroneous assumption about the xbmc library. Do you know if you have any tv shows without seasons or seasons without episodes in your xbmc library?

**Comment by tjoskar** [comment]
The error may appear from this line: https://github.com/tjoskar/script.episodeHunter/blob/eed85c9f12f2539fa2b0eaa5f6de10035e2aad63/resources/lib/sync/sync_series.py#L131

**Comment by AsianInvader** [comment]
I am currently using the 1.1.2 version.

It takes a while before displaying the error.

That is the likely cause, as I forgot I had one of my media hard drives shipped to my new flat. I can confirm if this was the problem in 5 days time when it arrives.

**Comment by tjoskar** [comment]
Could you try to download and install version 1.1.3 (https://github.com/tjoskar/script.episodeHunter/releases/tag/v1.1.3)? 

You install it by go to `Videos` and choose `Add-on` in the submenu and then `Get more...`. Press `..` and then `..` again. Enter `Install from zip file` and select the downloaded zip file (https://github.com/tjoskar/script.episodeHunter/archive/v1.1.3.zip).

Now. Go into the settings page for episodehunter and activate debug mode and then try to sync your tv episodes again. You will probably get the same error but this time it will be logged.

It would be nice if you want to share your log file, your log file should be placed here: `%APPDATA%\XBMC\` (open `run` and place `%APPDATA%\XBMC\` and press enter). The log file is named `kode.log`, you can either place it here on github or email it to info@episodehunter.tv.

(you can also upload your log file by installing `Kodi Log Uploader` http://kodi.wiki/view/Log_file/Easy)

**Comment by TepidWanderer** [comment]
In version 1.1.2 plugging in the hard drive fixed the problem.

**Comment by In2Deep** [comment]
Just in case someone else has this problem, I had this same error and updating to 1.1.3 fixed it for me.  Thanks!
